name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      # Install dependencies
      - run: npm ci

      # Build and output webpack stats to webpack-stats.json
      - run: npm run build

      # Send webpack stats and build information to RelativeCI
      - name: Send webpack stats to RelativeCI
        run: npx relative-ci-agent
        env:
          RELATIVE_CI_KEY: ${{ secrets.RELATIVE_CI_KEY }}
          DEBUG: ${{ secrets.DEBUG }}