name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      # Install dependencies
      - run: npm ci

      # Build and output webpack stats to webpack-stats.json and send webpack stats and build information to RelativeCI
      - run: npm run build
        env:
          webpackStatsFile: ./.next/stats.json
          key: ${{ secrets.RELATIVE_CI_KEY }}