name: 'coverage'
on:
    pull_request:
        branches:
            - main
            - dev
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: ArtiomTr/jest-coverage-report-action@v2